/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 career-area.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import * as THREE from 'three'
import { RigidBody } from '@react-three/rapier'

export default function CareerArea(props) {
  const { nodes, materials } = useGLTF('./models/career-area.glb')

  {/**
    Phoenix matcaps
  */}
  const [under_wing_matcap] = useLoader(THREE.TextureLoader, ['./matcaps/phoenix/phx-under-wing-orange.png'])
  
  return <>
    <group {...props} dispose={null}>
      <RigidBody type="fixed" friction={0.5}>
      <mesh geometry={nodes.career_ground.geometry} material={nodes.career_ground.material} position={[-11.72, 0.032, -1.327]} scale={[24.489, 31.979, 31.979]} />
      <mesh geometry={nodes.nrl_building.geometry} material={nodes.nrl_building.material} position={[14.456, 1.866, -15.214]} rotation={[0, -1.292, 0]} />
      <mesh geometry={nodes.PalmTree_1_Cylinder041.geometry} material={nodes.PalmTree_1_Cylinder041.material} position={[-12.228, 0.013, -11.458]} rotation={[Math.PI / 2, 0, 0]} scale={[1.452, 1.452, 0.921]} />
      <mesh geometry={nodes.PalmTree_3_Cylinder037.geometry} material={nodes.PalmTree_3_Cylinder037.material} position={[-10.547, 0.052, -18.253]} rotation={[Math.PI / 2, 0, 0]} scale={[1.515, 1.515, 0.961]} />
      <mesh geometry={nodes.asu.geometry} material={nodes.asu.material} position={[-12.089, 1.435, -14.402]} rotation={[1.475, 0.305, -1.261]} scale={0.772} />
      <mesh geometry={nodes.aws_emr_icon.geometry} material={nodes.aws_emr_icon.material} position={[9.677, 1.998, -26.324]} rotation={[0, -0.794, 0]} scale={[0.392, 0.17, 0.392]} />
      <mesh geometry={nodes.aws_glue_icon.geometry} material={nodes.aws_glue_icon.material} position={[9.732, 1.391, -24.753]} rotation={[-Math.PI, 0.794, 0]} scale={0.437} />
      <mesh geometry={nodes.aws_lambda_icon.geometry} material={nodes.aws_lambda_icon.material} position={[9.286, 1.306, -25.813]} rotation={[1.296, -0.269, 0.756]} scale={0.302} />
      <mesh geometry={nodes.vanguard_text.geometry} material={nodes.vanguard_text.material} position={[10.697, 2.7, -25.061]} rotation={[2.741, -0.736, 1.294]} scale={0.486} />
      <mesh geometry={nodes.vanguard_platform.geometry} material={nodes.vanguard_platform.material} position={[10.483, 1.64, -25.508]} rotation={[0, -0.794, 0]} scale={[0.507, 0.962, 0.507]} />
      <mesh geometry={nodes.python_icon.geometry} material={nodes.python_icon.material} position={[10.517, 2.795, -25.372]} rotation={[-Math.PI / 2, 0, -0.794]} scale={[0.036, 0.132, 0.036]} />
      <mesh geometry={nodes.antenna.geometry} material={nodes.antenna.material} position={[-8.503, 0.968, -25.625]} rotation={[0.693, 0.944, -1.667]} scale={0.077} />
      <mesh geometry={nodes.antenna_board.geometry} material={nodes.antenna_board.material} position={[-8.503, 0.968, -25.625]} rotation={[0.693, 0.944, -1.667]} scale={0.077} />
      <mesh geometry={nodes.solar_panels001.geometry} material={nodes.solar_panels001.material} position={[-7.134, 2.359, -26.927]} rotation={[-0.956, 0.056, -0.625]} scale={0.068} />
      <mesh geometry={nodes.lens.geometry} material={nodes.lens.material} position={[-8.766, 1.799, -25.312]} rotation={[0.693, 0.944, -1.667]} scale={0.351} />
      <mesh geometry={nodes.silver_sides.geometry} material={nodes.silver_sides.material} position={[-9.098, 1.631, -25.706]} rotation={[0.693, 0.944, -1.667]} scale={0.077} />
      <mesh geometry={nodes.black_sides.geometry} material={nodes.black_sides.material} position={[-9.098, 1.631, -25.706]} rotation={[0.693, 0.944, -1.667]} scale={0.077} />
      <mesh geometry={nodes.rocket_stand_ring.geometry} material={nodes.rocket_stand_ring.material} position={[1.361, 0.823, -28.471]} scale={0.113} />
      <mesh geometry={nodes.rocket_platform.geometry} material={nodes.rocket_platform.material} position={[1.377, 0.351, -28.453]} rotation={[0, 0.785, 0]} scale={0.113} />
      <mesh geometry={nodes.flame_tunnel.geometry} material={nodes.flame_tunnel.material} position={[0.107, 0.278, -29.722]} rotation={[-Math.PI, 0.786, -Math.PI]} scale={0.113} />
      <mesh geometry={nodes.rocket_cradle.geometry} material={nodes.rocket_cradle.material} position={[1.735, 0.737, -28.729]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.013} />
      <mesh geometry={nodes.rocket.geometry} material={nodes.rocket.material} position={[1.359, 0.84, -28.373]} rotation={[0, -1.571, 0]} scale={0.113} />
      <mesh geometry={nodes.Rock_Moss_4_Cube023.geometry} material={nodes.Rock_Moss_4_Cube023.material} position={[6.047, 0.215, -29.156]} rotation={[Math.PI / 2, 0, 1.686]} />
      <mesh geometry={nodes.Rock_4_Cube002.geometry} material={nodes.Rock_4_Cube002.material} position={[-12.286, 0.243, -19.29]} rotation={[Math.PI / 2, 0, -0.186]} />
      <mesh geometry={nodes.Rock_4_Cube003.geometry} material={nodes.Rock_4_Cube003.material} position={[-6.214, 0.243, -27.5]} rotation={[Math.PI / 2, 0, -2.819]} />
      <mesh geometry={nodes.Rock_4_Cube004.geometry} material={nodes.Rock_4_Cube004.material} position={[11.495, 0.243, -20.727]} rotation={[Math.PI / 2, 0, 2.89]} />
      <mesh geometry={nodes.Rock_Moss_5_Cube001.geometry} material={nodes.Rock_Moss_5_Cube001.material} position={[12.461, -0.099, -20.041]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_4_Cube001.geometry} material={nodes.Rock_Moss_4_Cube001.material} position={[-4.726, 0.215, -26.352]} rotation={[Math.PI / 2, 0, 1.686]} />
      <mesh geometry={nodes.Rock_Moss_1_Cube001.geometry} material={nodes.Rock_Moss_1_Cube001.material} position={[-3.466, 0.165, -29.787]} rotation={[Math.PI / 2, 0, 0]} scale={[2.583, 2.583, 1.626]} />
      <mesh geometry={nodes.Rock_1_Cube003.geometry} material={nodes.Rock_1_Cube003.material} position={[13.822, -0.013, -10.093]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_1_Cube005.geometry} material={nodes.Rock_1_Cube005.material} position={[6.707, -0.013, -26.197]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_1_Cube006.geometry} material={nodes.Rock_1_Cube006.material} position={[3.462, -0.013, -29.956]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_1_Cube007.geometry} material={nodes.Rock_1_Cube007.material} position={[-8.851, -0.013, -22.322]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_1_Cube008.geometry} material={nodes.Rock_1_Cube008.material} position={[-12.412, -0.013, -21.294]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_6_Cube001.geometry} material={nodes.Rock_Moss_6_Cube001.material} position={[5.712, -0.014, -26.615]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_6_Cube002.geometry} material={nodes.Rock_Moss_6_Cube002.material} position={[-9.213, -0.014, -20.09]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_6_Cube003.geometry} material={nodes.Rock_Moss_6_Cube003.material} position={[-11.507, -0.014, -22.701]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_7_Cube001.geometry} material={nodes.Rock_7_Cube001.material} position={[15.472, 0.22, -10.134]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_2_Cube004.geometry} material={nodes.Rock_2_Cube004.material} position={[13.795, 0.032, -19.716]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube003.geometry} material={nodes.Rock_Moss_2_Cube003.material} position={[-10.998, 0.07, -19.84]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube004.geometry} material={nodes.Rock_Moss_2_Cube004.material} position={[-1.797, 0.07, -29.986]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube005.geometry} material={nodes.Rock_Moss_2_Cube005.material} position={[4.422, 0.07, -28.993]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube006.geometry} material={nodes.Rock_Moss_2_Cube006.material} position={[4.185, 0.07, -27.369]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube007.geometry} material={nodes.Rock_Moss_2_Cube007.material} position={[11.692, 0.07, -23.587]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_2_Cube008.geometry} material={nodes.Rock_Moss_2_Cube008.material} position={[12.131, 0.07, -18.547]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_3_Cube003.geometry} material={nodes.Rock_3_Cube003.material} position={[-11.511, 0.061, -18.053]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_3_Cube004.geometry} material={nodes.Rock_3_Cube004.material} position={[-1.126, 0.061, -27.793]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_3_Cube005.geometry} material={nodes.Rock_3_Cube005.material} position={[-2.691, 0.061, -28.201]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_3_Cube006.geometry} material={nodes.Rock_3_Cube006.material} position={[4.654, 0.061, -30.656]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rock_Moss_1_Cube002.geometry} material={nodes.Rock_Moss_1_Cube002.material} position={[14.729, 0.165, -11.503]} rotation={[Math.PI / 2, 0, 2.507]} scale={1.491} />
      <mesh geometry={nodes.hedge012.geometry} material={nodes.hedge012.material} position={[6.811, 1.064, -27.727]} rotation={[0, -0.587, 0]} />
      <mesh geometry={nodes['tall-stem2002'].geometry} material={nodes['tall-stem2002'].material} position={[-4.531, 0.358, -28.12]} rotation={[0, 0.143, 0]} scale={[0.037, 0.164, 0.037]} />
      <mesh geometry={nodes['tall-bush2'].geometry} material={nodes['tall-bush2'].material} position={[-10.063, 1.181, -21.264]} rotation={[Math.PI, -1.145, Math.PI]} scale={0.231} />
      <mesh geometry={nodes['tall-bush1004'].geometry} material={nodes['tall-bush1004'].material} position={[12.432, 1.91, -21.648]} rotation={[-Math.PI, 0.481, -Math.PI]} scale={0.216} />
      <mesh geometry={nodes['wide-bush2001'].geometry} material={nodes['wide-bush2001'].material} position={[-4.493, 0.819, -27.943]} rotation={[-Math.PI, 0.638, -Math.PI]} scale={0.16} />
      <mesh geometry={nodes['tall-stem1003'].geometry} material={nodes['tall-stem1003'].material} position={[12.587, 0.486, -21.788]} rotation={[Math.PI, -1.135, Math.PI]} scale={[0.051, 0.222, 0.051]} />
      <mesh geometry={nodes.stem1007.geometry} material={nodes.stem1007.material} position={[16.84, 0.243, -11.07]} rotation={[Math.PI, -1.212, Math.PI]} scale={[0.033, 0.241, 0.033]} />
      <mesh geometry={nodes['wide-bush1002'].geometry} material={nodes['wide-bush1002'].material} position={[16.806, 0.634, -10.983]} rotation={[0, 1.212, 0]} scale={[0.201, 0.319, 0.201]} />
      <mesh geometry={nodes['tall-stem2004'].geometry} material={nodes['tall-stem2004'].material} position={[-10.294, 0.513, -21.481]} rotation={[0, -1.349, 0]} scale={[0.054, 0.236, 0.054]} />
      <mesh geometry={nodes.stem2008.geometry} material={nodes.stem2008.material} position={[7.029, 0.356, -27.506]} rotation={[0, -0.587, 0]} />
      <mesh geometry={nodes.fence_segment008.geometry} material={nodes.fence_segment008.material} position={[-21.855, 1.693, -14.945]} rotation={[-Math.PI / 2, 0, 1.571]} scale={[-0.185, -0.022, -1.866]} />
      <mesh geometry={nodes.fence_segment001.geometry} material={nodes.fence_segment001.material} position={[4.575, 1.693, -36.285]} rotation={[-Math.PI / 2, 0, 0.001]} scale={[-0.185, -0.022, -1.866]} />
      <mesh geometry={nodes.fence_segment003.geometry} material={nodes.fence_segment003.material} position={[21.125, 1.693, -14.633]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[-0.185, -0.022, -1.866]} />
      <mesh geometry={nodes.fence_segment015.geometry} material={nodes.fence_segment015.material} position={[-17.408, 1.407, -36.289]} rotation={[-Math.PI / 2, 0, 0.001]} scale={[-0.185, -0.022, -1.866]} />
      <mesh geometry={nodes.claws.geometry} material={nodes.claws.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.beak.geometry} material={nodes.beak.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.under_wing.geometry} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]}>
        <meshMatcapMaterial matcap={under_wing_matcap} />
      </mesh>
      <mesh geometry={nodes.body.geometry} material={nodes.body.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.eye.geometry} material={nodes.eye.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.dark_gray_edges.geometry} material={nodes.dark_gray_edges.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.lite_gray_panels.geometry} material={nodes.lite_gray_panels.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.solar_panels.geometry} material={nodes.solar_panels.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.gray_cam_ring.geometry} material={nodes.gray_cam_ring.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.blue_cam_ring.geometry} material={nodes.blue_cam_ring.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.land.geometry} material={nodes.land.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.water.geometry} material={nodes.water.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.text_blue_ring.geometry} material={nodes.text_blue_ring.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.text.geometry} material={nodes.text.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.space.geometry} material={nodes.space.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      <mesh geometry={nodes.stars.geometry} material={nodes.stars.material} position={[-7.214, 1.13, -24.988]} rotation={[1.247, 0.251, -0.638]} scale={[0.538, 0.97, 0.538]} />
      </RigidBody>
    </group>
  </>
}

useGLTF.preload('/career-area.glb')
