/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 projects-area.glb 
*/

import { useGLTF, useTexture } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

import GenericArea from 'src/components/areas/GenericArea.jsx'
import FogWall from 'src/components/FogWall.jsx'


export default function ProjectsArea(props) {
  const { nodes } = useGLTF('./models/projects-area.glb')
  console.log(nodes)
  const groundTexture = useTexture('./textures/projects-area-baked.jpg')
  groundTexture.flipY = false

  return <>
    <group {...props} dispose={null}>

      <GenericArea nodes={nodes} exclusions={[nodes.projects_ground, nodes.fog_wall]} />

      {/* Floor with baked material */}
      <RigidBody type="fixed">
        <mesh key={nodes.projects_ground.uuid}
              geometry={nodes.projects_ground.geometry} 
              position={nodes.projects_ground.position} 
              rotation={nodes.projects_ground.rotation} 
              scale={nodes.projects_ground.scale}>

          <meshBasicMaterial map={groundTexture} />

        </mesh>
      </RigidBody>

      {/* Fog wall */}
      <FogWall wallMesh={nodes.fog_wall} />
      
    </group>
  </>
}

useGLTF.preload('./models/projects-area.glb')
