/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 projects-area.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import MatcapManager from 'src/MatcapManager.js'
import GenericArea from 'src/components/areas/GenericArea.jsx'

export default function ProjectsArea(props) {
  const { nodes, materials } = useGLTF('./models/projects-area.glb')
  const matcapManager = new MatcapManager()
  return <>
    <group {...props} dispose={null}>

      <GenericArea nodes={nodes} />
      
    </group>
  </>
}

useGLTF.preload('./models/projects-area.glb')
