/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rabbit-hole-area.glb 
*/

import { useRef } from 'react'
import { useGLTF, useTexture, shaderMaterial, Float, Text } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import * as THREE from 'three'
import { extend, useFrame } from '@react-three/fiber'
import { v4 as uuidv4 } from 'uuid'

import portalVertexShader from 'src/shaders/portal/vertex.glsl' // TODO not a big fan of paths like this
import portalFragmentShader from 'src/shaders/portal/fragment.glsl'
import GenericArea from 'src/components/areas/GenericArea.jsx'


const PortalMaterial = shaderMaterial(
    {
        uTime: 0,
        uColorStart: new THREE.Color('#F2E3C6'), // Copilot came up with the inner color!
        uColorEnd: new THREE.Color('#BFA26B')
    },
    portalVertexShader,
    portalFragmentShader
)

extend({ PortalMaterial })

export default function RabbitHoleArea(props) {

    const { nodes } = useGLTF('/models/rabbit-hole-area.glb')

    const frontGroundTexture = useTexture('./textures/rabbit-hole-front-baked.jpg')
    frontGroundTexture.flipY = false

    const rearGroundTexture = useTexture('./textures/rabbit-hole-rear-baked.jpg')
    rearGroundTexture.flipY = false

    // Animate portal
    const portalMaterialRef = useRef()
    useFrame((state, delta) => {
        portalMaterialRef.current.uTime += delta
    })

    /**
     * Currently teleports rabbit back to beginning.
     * Real implementation reserved for v1.0
     */
    function portalAction(payload) {

        const rabbitRef = payload.other.rigidBody.userData.rabbitRef
        rabbitRef.current.setTranslation({ x: 0, y: 0.25, z: 0 })
        
    }

    return <>
        <group {...props} dispose={null}>
            <GenericArea nodes={nodes} exclusions={[nodes.rabbit_hole_ground_front, nodes.rabbit_hole_ground_rear,
                                                    nodes.rabbit_hole_portal, nodes.rabbit_hole_ground]} />

            {/* Floors with baked materials */}
            <RigidBody type="fixed">
                <mesh key={nodes.rabbit_hole_ground_front.uuid}
                      geometry={nodes.rabbit_hole_ground_front.geometry} 
                      position={nodes.rabbit_hole_ground_front.position} 
                      rotation={nodes.rabbit_hole_ground_front.rotation} 
                      scale={nodes.rabbit_hole_ground_front.scale}>

                    <meshBasicMaterial map={frontGroundTexture} />

                </mesh>
            </RigidBody>

            {/* Add detailed colliders to the section containing the rabbit hole */}
            <RigidBody type="fixed" colliders="trimesh" key={uuidv4()}>
                <mesh key={nodes.rabbit_hole_ground_rear.uuid}
                      geometry={nodes.rabbit_hole_ground_rear.geometry} 
                      position={nodes.rabbit_hole_ground_rear.position} 
                      rotation={nodes.rabbit_hole_ground_rear.rotation} 
                      scale={nodes.rabbit_hole_ground_rear.scale}>

                    <meshBasicMaterial map={rearGroundTexture} />

                </mesh>
            </RigidBody>

            {/* The portal is in the exclusions so it shouldn't be added by the generic area.
                Add it here so we can contol the shader material
            */}
            <RigidBody type="fixed"
                       key={uuidv4()} 
                       colliders="trimesh" 
                       sensor={true}
                       onIntersectionEnter={(payload) => portalAction(payload)}
            >
                <mesh key={nodes.rabbit_hole_portal.uuid}
                    geometry={nodes.rabbit_hole_portal.geometry}
                    position={[nodes.rabbit_hole_portal.position.x, nodes.rabbit_hole_portal.position.y, nodes.rabbit_hole_portal.position.z]} 
                    rotation={[nodes.rabbit_hole_portal.rotation._x, nodes.rabbit_hole_portal.rotation._y, nodes.rabbit_hole_portal.rotation._z]} 
                    scale={[nodes.rabbit_hole_portal.scale.x, nodes.rabbit_hole_portal.scale.y, nodes.rabbit_hole_portal.scale.z]}>

                        <portalMaterial ref={portalMaterialRef} />

                </mesh>
            </RigidBody>

            {/* 
                TODO remove in final release
                Indicates to Beta users that the rabbit hole feature is not currently available
            */}
            <Float floatIntensity={ 0.25 } rotationIntensity={ 0.25 }>
                <Text
                    font="./fonts/bebas-neue-v9-latin-regular.woff"
                    scale={ 0.5 }
                    maxWidth={ 5 }
                    lineHeight={ 0.75 }
                    textAlign="center"
                    position={ [-13, 1.5, -0.5] }
                    rotation-y={ Math.PI/2 }
                    >
                    Beta Users! Note this is not yet fully featured.
                    <meshBasicMaterial toneMapped={ false } />
                </Text>
            </Float>
               
        </group>
    </>
}

useGLTF.preload('./models/rabbit-hole-area.glb')
