/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rabbit.glb 
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rabbit.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" rotation={[0.015, 0, 0]} scale={4.716}>
          <primitive object={nodes.pelvisC} />
          <primitive object={nodes.control_frontl} />
          <primitive object={nodes.pole_target_frontl} />
          <primitive object={nodes.control_frontr} />
          <primitive object={nodes.pole_target_frontr} />
          <primitive object={nodes.control_backl} />
          <primitive object={nodes.pole_backl} />
          <primitive object={nodes.control_backr} />
          <primitive object={nodes.pole_backr} />
          <group name="rabbit">
            <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={materials.brown} skeleton={nodes.Plane.skeleton} />
            <skinnedMesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.white} skeleton={nodes.Plane_1.skeleton} />
            <skinnedMesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.black} skeleton={nodes.Plane_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rabbit.glb')
